### ISSUE TITLE
Question regarding MCTQ-Core

### ISSUE THREAD

**Issue by andreifoldes** [ropensci/mctq#35]
Greetings,

Thank you for this package. I hope its not terribly misplace, but wanted to ask whether there is any article relating to the function/rationale behind the drawing displayed in https://www.thewep.org/documentations/mctq/item/english-mctq-core

**Comment by danielvartan** [comment]
Hi Andrei,

Not at all misplaced.

Can you be more specific? Are you referring to the guiding images?

![image](https://github.com/user-attachments/assets/550eda18-3e97-42f5-ac04-52d1dde38144)

You may be looking for MCTQ's key articles. You can find them [here](https://www.thewep.org/documentations/mctq/item/mctq#:~:text=Key%20MCTQ%20literature%C2%A0). Here are the main ones:

Roenneberg, T., Wirz-Justice, A., & Merrow, M. (2003). Life between clocks: daily temporal patterns of human chronotypes. *Journal of Biological Rhythms*, *18*(1), 80–90. https://doi.org/10.1177/0748730402239679

Roenneberg, T., Allebrandt, K. V., Merrow, M., & Vetter, C. (2012). Social jetlag and obesity. *Current Biology*, *22*(10), 939–943. https://doi.org/10.1016/j.cub.2012.03.038

Roenneberg, T., Pilz, L. K., Zerbini, G., & Winnebeck, E. C. (2019). Chronotype and social jetlag: a (self-) critical review. Biology, *8*(3), 54. https://doi.org/10.3390/biology8030054
